name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
      
      - name: Docker Compose Run
        run: |
          docker-compose up -d
          sleep 10

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade-strategy=only-if-needed

      - name: Install dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pipenv sync --dev
          
      - name: DB Migrate
        run: |
          cd alembic/
          pipenv run db-migrate

      - name: Run Lint
        run: |
          pipenv run lint
          
      - name: Run Test
        run: |
          pipenv run test
