name: ci

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

env:
  DOCKER_IMAGE_CACHE_PATH: docker-image
  POSTGRES_VERSION: 15.2

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade-strategy=only-if-needed

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pipenv sync --dev

      - name: Run Lint
        run: |
          pipenv run lint

      - name: Docker Compose Run
        run: |
          docker-compose up -d
          sleep 10
          
      - name: Run Test
        run: |
          pipenv run test
