name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
      
      - name: Docker Compose Run
        run: |
          docker-compose up -d
          sleep 10

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade-strategy=only-if-needed

      - name: Install dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pipenv sync --dev

      - name: Run Lint
        run: |
          pipenv run lint
          
      - name: Run Test
        run: |
          pipenv run test
